"""Add new Tenant fields

Revision ID: 91d725d72296
Revises: 1f7f4ccdbb39
Create Date: 2026-03-20 01:29:51.005589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d725d72296'
down_revision: Union[str, None] = '1f7f4ccdbb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
